version: 0.2
phases:
  install:
    runtime-version:
      dotnet: latest
  pre_build:
    commands:
      - echo login to code artifact
      - aws codeartifact login --tool dotnet --repository helpmycase --domain helpmycase --domain-owner 619680812856
  build:
    commands:
      - echo Build dotnet application
      - dotnet build --configuration Release -p:Version=1.0.$CODEBUILD_BUILD_NUMBER
      - echo Pack nuget package
      - dotnet pack -c Release
  post_build:
    commands:
      - echo Nuget push
      - dotnet nuget push bin/Release/Api.Database.MySql.1.0.$CODEBUILD_BUILD_NUMBER.nupkg --source helpmycase/helpmycase